### ISSUE TITLE
How to get involved

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#103]
probably a good page to have at the end of each chapter?

**Comment by stonemaster** [comment]
Actually I wouldn't know what to put in there. And with all your in-depth PRs I think the reader has a lot of stuff to go from there ;-)

**Comment by wilzbach** [comment]
Maybe we can have at the end a
a)  "Your help is need", "How to get involved with the community" section?
b) Good projects to work on
c) Dive deeper (basically reposting the links from welcome.md)

**Comment by stonemaster** [comment]
Anyone who likes the language and want to follow its development will at some point go to the mailing list /forum at dlang.org. The tour should be about giving a first impression of the language with in-depth links to other resources so I don't think we need any other publicity for other projects - that will come with all the other resources already provided within the tour (and available at dlang.org)
