### ISSUE TITLE
Make keyboard shortcuts clickable

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#114]
I just realized that I wanted to click that for the second time.

**Comment by stonemaster** [comment]
Do you mean the 1. link at the bottom or 2. when the  shortcut box actually pops up?
1. could be fixed (maybe) but 2. is a wontfix because the angular highlight library doesn't support this.
Then, why using the mouse when there are keyboard shortcuts :-)

**Comment by wilzbach** [comment]
1) - yeah I agree, but as said I realized that I was having the bad habit of trying anyways, so maybe other people are similar to me :/

**Comment by stonemaster** [comment]
If it's just 1.) it will be a quite simple fix.

**Comment by wilzbach** [comment]
I never needed it, so I will just close it for now.
