### ISSUE TITLE
Collect telemetry about usage

### ISSUE THREAD

**Issue by stonemaster** [stonemaster/dlang-tour#12]
Collect visits per section, number of compiles (incl. failures) and create overview page to show usage stats of the tour.

**Comment by greenify** [comment]
can't you include Google Analytics for a start? It's free an pretty easy to setup.

**Comment by stonemaster** [comment]
Good suggestion. I already used Google Analytics so I confirm I would be easy to integrate it into the current solution. Basically Google Analytics could always be used even if some more fancy telemetry will be built at a later stage.
