### ISSUE TITLE
add gem about variadiac functions

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#126]
http://dlang.org/variadic-function-templates.html

**Comment by stonemaster** [comment]
I am stil undecided on this one. Maybe it could be too little value added because using the basic knowledge one gets quickly acquainted to variadic functions (at least those in D).

**Comment by wilzbach** [comment]
Maybe we can add it as part of another gem?

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#6
