### ISSUE TITLE
add gem about inline assembler

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#128]
https://dlang.org/spec/iasm.html

**Comment by stonemaster** [comment]
That would be nice.

**Comment by stonemaster** [comment]
> http://asm.dlang.org is a great service and we should mention this - maybe related with #128.

**Comment by wilzbach** [comment]
[Goto](https://dlang.org/spec/statement.html#GotoStatement) is a very powerful construct in D, so I think I might fit into this section too ;-)

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#4
