### ISSUE TITLE
Translation in multiple languages

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#132]
We should probably set a milestone once it's stable enough, s.t. we can start translating in multiple languages. So I keep this here open for people to volunteer for their language and notification once we want to start going multi-lingual:

@buggins offered to translate into Russian
@wilzbach offered to translate to German

It probably makes sense then to put the translated commit as plain text comment in the regarding language, s.t. it's easy to update the languages once in a while.

**Comment by wilzbach** [comment]
@acehreli would you be willing to translate it to Turkish? (once it's moderately stable)

**Comment by acehreli** [comment]
Of course! :)

Ali

**Comment by stonemaster** [comment]
Thanks all translators for their help! Lets make that happen when the storm of pull requests and changes has passed :-)

**Comment by meatatt** [comment]
Willing to! But @DlangRen is translating "Prg in D" into Chinese at present. As the only active dlang community in China, we are extermly short of volunteers. So we want to finish this project first due to the lack of helping hands. We still waiting for an upturn of dlang in China. Anyway we will start translating this as soon as the current one is completed.

**Comment by acehreli** [comment]
@meatatt, Chinese community may be slow but rest assured, perhaps due to large population, ddili.org gets almost equal visitors from China and US. (There has been months where Chinese visitors were more than US visitors.)

This month so far:

US
Pages: 28,412
Hits: 32,741
Bandwidth: 1.18 GB

China
Pages: 23,776
Hits: 24,516
Bandwidth: 1.04 GB

The next country in line is Turkey with about 25% of those numbers.

Ali

**Comment by meatatt** [comment]
@acehreli Wow! This is truly beyond our imagination. Thank you :)

**Comment by wilzbach** [comment]
Just a quick update from the dev team, with #276 the last real blocking PR for multi-lingual just went in.

Also we now have separated each chapter into a single file, s.t. translation will be easier and we now feature an edit button on the tour that directly takes one to the corresponding markdown file.

@stonemaster and I will work on getting basic macro support (#55) to avoid putting redundant HTML into the markdown. Meanwhile we encourage everyone to read through the tour and find nitpicks.

I guess after another heavy round of reviewing and nitpicking, the fight for the first translation may begin ;-)

**Comment by claudiug** [comment]
guys, for sure I can translate in Romanian, and also my colleague, Louis will do it in French.

just ping us :)

**Comment by stonemaster** [comment]
@claudiug Awesome! Give us a couple weeks for polishing and then we'll be ready for the translation marathon :-)

**Comment by lodo1995** [comment]
Hi guys,
do you already have someone who can translate in italian?
If not, I'd be happy to contribute.
(just ping me when it's time to do it)

**Comment by stonemaster** [comment]
@lodo1995 Not yet! Awesome, thanks we'll come back to you!

**Comment by stonemaster** [comment]
Check list of translators:

- [ ] **German**: @wilzbach, @stonemaster
- [ ] **Turkish**: @acehreli 
- [ ] **Russian**: @buggins
- [ ] **French**: _Louis_
- [ ] **Romanian**: @claudiug 
- [ ] **Chinese**: @meatatt 

Must haves to be done before translation can be started:
- [ ] Agreement that tour contents in English meet overall expectations and next round of reviewing has passed.
- [ ] #55 is implemented
- [ ] ...

**Comment by llaine** [comment]
For sure I'm in @stonemaster !!

**Comment by wilzbach** [comment]
> Check list of translators:
> Chinese: @meatatt
> French: @llaine
> German: @wilzbach, @stonemaster
> Romanian: @claudiug
> Russian: @buggins
> Turkish: @acehreli

Hey all time has passed and @stonemaster and I feel that the tour has matured enough to be ready for the translation into multiple languages. @dmi7ry [has already done](https://github.com/stonemaster/dlang-tour/pull/384) a huge step forward for the Russian translation and I [started](https://github.com/stonemaster/dlang-tour/pulls) myself with the German one.

Hence I would look to share my experience of translating the tour in German with you and I prepared a small guide for translators:

https://github.com/stonemaster/dlang-tour/wiki/Tips-for-translators

And I have also written a small, optional  tool that automates submitting multiple PRs:

https://github.com/wilzbach/splitup-prs

(It's not perfect, but it already saves time for me)

Some key points
- please submit a PR for each file as it makes it makes the reviewing easier (my tool can help you to automate this)
- the tour isn't perfect yet and while translating you will have a close look at it -> don't hesitate to submit a PR even if it's just for one word. This can be done most conveniently via the edit button on the top right of the content
- the [translator guide](https://github.com/stonemaster/dlang-tour/wiki/Tips-for-translators) should describe most issues you may run into, but really just ping us for help
- I know that it's quite a work that is ahead of us, so your help is really, really appreciated!
- I think once `welcome` + `basic` chapter are fully merged, we will start listing it on tour.dlang.org ;-)

Let's get the party started :tada:

**Comment by wilzbach** [comment]
> Let's get the party started  :tada: and let the race begin!

Hey all,

just a quick update from my side. We have seen such a massive increase in PRs for the translations that we split them up into submodules (#454).
Already a huge thanks to our already started party teams: Sweden (@vladdeSV @vild @nordlow  @jacob-carlborg)
Italia (@lodo1995 @trikko), Russia (@Dicebot @DmitryOlshansky @dmi7ry) and Germany (@WebFreak001 @stonemaster ...).

In case you didn't follow this closely: the organization [dlang-tour](https://github.com/dlang-tour) has been founded and contains a repo for each language which will be embed into the main tour & some languages have already been linked:

http://tour.dlang.io/tour/sv/welcome/welcome-to-d
http://tour.dlang.io/tour/it/welcome/welcome-to-d
http://tour.dlang.io/tour/de/welcome/welcome-to-d

(they are still WIP and thus not linked from the main repo)

From the process above nearly nothing should have changed except for two things:
- You can now make PRs against the language repo (there's a CI in-place which will check that all examples script are runnable)
- You are now in charge of your own language repo (all of you should have gotten an invitation to join their language repo)

For my readers from the future: if you want to start a translation of a new language or join an existing team, just ping me or @stonemaster, we are happy to help.

Last but not least don't hesitate to ask questions if you run into troubles and don't forgot to make a PR for every file (see above for more tips).

**Comment by wilzbach** [comment]
I am closing this issue now as the translations are on a good way and in same cases already finished :)
If you run into any issue, feel free to open a new issue at your repository and ping @dlang-tour/base (this works only for repos at the dlang-tour) or alternatively open an issue here.
Thanks a lot for all the great work that you are doing!
