### ISSUE TITLE
gem: Using Fibers with ranges

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#133]
This is one of my favorite features in D, but it took me a while to discover this.
This allows one to write pretty sophisticated lazy algorithms by just saving keeping a reference to the stack.
Ali had a great talk about this year -> http://dconf.org/2016/talks/cehreli.html

```
import std.concurrency: Generator,yield;
auto r = new Generator!int(
{
    foreach (i; 1 .. 10)
        yield(i);
});

import std.range: iota;
import std.algorithm.comparison: equal;
assert(r.equal(iota(1, 10)));
```

https://dlang.org/library/std/concurrency/generator.html

**Comment by stonemaster** [comment]
That's a good one. There is already fiber's section maybe it fits  there.

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#7
