### ISSUE TITLE
Sections in which the playground code does not compile

### ISSUE THREAD

**Issue by SnirkImmington** [stonemaster/dlang-tour#134]
This is a list of compiler errors that the default playground snippets have, in cases where they are probably not intended.
(I would have submitted a pull request, but I couldn't find the source for the snippets in this repository as promised)
**I am new to the language and went through the tour as a newcomer, then noticed one of the examples didn't work.
I spent 45 going through the whole tour again and found what I think are unintended compilation errors.**
_I'm not trying to criticize the tour or anything! If any these are_ supposed _to be fixed by the reader, I'm sorry._
(These are retrieved from http://tour.dlang.org/tour/ from Wednesday, May 18th around 14:30 EST, clicking the run button)

- [x] **Basics/3 - Memory** http://tour.dlang.org/tour/basics/3

The example with pointer arithmetic is missing a valuable `p`. Perhaps pass it into the method?
```d
void unsafeFun()
{
    int* fiddling = p + 5; // onlineapp.d(12): Error: undefined identifier 'p'
}
```
- [x] **Basics/4 - Storage Classes** http://tour.dlang.org/tour/basics/4

The playground is complaining about the asserts. Is the syntax wrong?
```
onlineapp.d(6): Error: found ';' when expecting ')' following template argument list
onlineapp.d(6): Error: found ')' when expecting ';'
onlineapp.d(11): Error: found ';' when expecting ')' following template argument list
onlineapp.d(11): Error: found ')' when expecting ';'
onlineapp.d(21): Error: found ';' when expecting ')' following template argument list
onlineapp.d(21): Error: found ')' when expecting ';'
onlineapp.d(25): Error: (arguments) expected following immutable(int)
onlineapp.d(25): Error: found ';' when expecting ')' following template argument list
onlineapp.d(25): Error: found ')' when expecting ';'
```
- [x] **Basics/5 - Control Flow** http://tour.dlang.org/tour/basics/5

Another undeclared variable `p`. Was this meant to be a different case match?
```d
    switch(5) {
        case 0: .. case 9:
            writeln(c, " is within 0-9"); // onlineapp.d(10): Error: undefined identifier 'c'
            break; // necessary!
```

- [x] **Basics/8 - Arrays** http://tour.dlang.org/tour/basics/8

Assertion at line 38 fails. Does the algorithm work as expected?
```d
    writeln("Before: ", toBeEncrypted);
    auto encrypted = encrypt(toBeEncrypted, 16);
    writeln("After: ", encrypted);

    // Make sure we the algorithm works
    // as expected
    assert(encrypted == [ 'm','u','b','s','e', // core.exception.AssertError@onlineapp.d(38): Assertion failure
            'c','u','j','e','t' ]);
```

- [x] **Gems/2 - Scope Guards** http://tour.dlang.org/tour/gems/2

This was the first issue I came across which prompted me forking this project, but I couldn't find the source of the examples.
You're missing a cast on `malloc`:
```d
    // scope guards allow placing allocations
    // and their clean up code next to each
    // other
    import core.stdc.stdlib;
    int* p = malloc(int.sizeof); // onlineapp.d(24): Error: cannot implicitly convert expression (malloc(4LU)) of type void* to int*
    scope(exit) free(p);
```

- [x] **Gems:7 - Functional Programming** http://tour.dlang.org/tour/gems/7

This one's over my head, but it looks like it would be awesome if it compiled:
```d
   // memoize caches the result of the function
    // call depending on the input parameters.
    // pure functions are great for that!
    alias fastMedian = memoize!(median!int);

    writeln([7, 5, 3].fastMedian); // onlineapp.d(23): Error: no property 'fastMedian' for type 'int[]'
    // result will be cached!
    writeln([7, 5, 3].fastMedian); // onlineapp.d(25): Error: no property 'fastMedian' for type 'int[]'
```

- [x] **Gems:8 - Contract Programming** http://tour.dlang.org/tour/gems/8

Not sure what's wrong, but a month invariant fails:
```d
    invariant() {
        assert(year >= 0);
        assert(month >= 1 && month <= 12); // core.exception.AssertError@onlineapp.d(18): Assertion failure
        assert(day >= 1 && day <= 31);
    }
```

I tried to ignore all the errors that were meant to be filled in by the reader (i.e. with `Vector3` in basics/7).
Perhaps if you fix #57 and auto-test the examples before publishing updates these issues wouldn't happen.

**Comment by stonemaster** [comment]
Thank you for your very thorough report and the time you invested in checking all examples for compiling! I am very sorry about that. Currently there is no automatic checking for the code examples (you mentioned #57 already) and I just didn't do a thorough checking of the latest changes. This is quite embarrassing and should not be something a newcomer should be exposed to as it gives a bad impression on the language. I fixed all compilation errors but two:
- Basics/8 is an exercise so the assertion is "by design" if the according function isn't implemented.
- Gems/8 is actually something that is triggered by the example code. There is a comment in the `main()` function which explains that the next line will make the invariant fail. 

Again thank you very much for your work. With this issue, #57 will definitely get a high priority and any other code examples changes will be verified very carefully.

**Comment by stonemaster** [comment]
Btw. it might take about 15 minutes until you will see the code example changes actually online.
