### ISSUE TITLE
Intro to Numerical Programming with D

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#136]
Basically a 101 guide to ndslice and the upcoming numerical packages from [mir](https://github.com/libmir/mir).

Ping @9il

Maybe it can be based on [mir.rocks](http://mir.rocks/)

@stonemaster as long as mir is in development and not in Phobos, we need to download the sources via dub or git clone to be able to properly rdmd it. Have you already made some thoughts about this?
(this is also needed for other tours like the GameDev one)

The easiest way is probably to git clone the latest mir version on every deploy to the dmd include directory (usually `/usr/include/dlang/`)

**Comment by stonemaster** [comment]
This is also a duplicate #27 where ideas may be collected.
