### ISSUE TITLE
Split up in folder

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#137]
It's probably a lot easier for user to find the file they want to edit if we split-up the huge markdown file into a folder with multiple smaller files.

**Comment by wilzbach** [comment]
One thing that I realized is that while this approach seems the better way to go, because we will have slim files and can better link to them, is that we would need to define the order somehow. This could be done with the file title, e.g. 01_ or an index file. 
Both have disadvantages, what do you prefer?

**Comment by stonemaster** [comment]
I think I would prefer the 01_title.md way. Although reordering could be a pain this would allow to put as much information in the file name (which is then in the correct order locally when listing files too) and we don't need an additional file (that needs be edited which might be error-prone).
This could also be done for chapters using the same scheme for folders; this makes the internal hard-coding redundant 👍

**Comment by wilzbach** [comment]
Great - I prefer the file name pproach too :)

**Comment by wilzbach** [comment]
Something very important that we should keep in mind is that whenever we rename something (especially with the 05_...), we should have some easy way to remember this and redirect to the new content.
Breaking links is not nice.

**Comment by wilzbach** [comment]
solved by #224 :)
