### ISSUE TITLE
use tour.dlang.io

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#14]
I already created an A entry to 46.101.210.109, so feel to change your server config.

**Comment by stonemaster** [comment]
It's working already. There is no special server config needed because the tour doesn't need to know its hostname. The current server is a private server with very limited resources so before going to public the tour has to move anyway.

**Comment by stonemaster** [comment]
@wilzbach Could you change the IP address of tour.dlang.io to 216.117.130.254? This will be the official server that also tour.dlang.org is pointing to.

**Comment by wilzbach** [comment]
> Could you change the IP address of tour.dlang.io to 216.117.130.254? This will be the official server that also tour.dlang.org is pointing to.

That's great news! DNS is updated and should be proprogated in the next minutes/hour.
