### ISSUE TITLE
explain inout

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#146]
`inout` is a pretty confusing feature, so we should definitely explain it somewhere.

https://dlang.org/spec/const3.html
http://forum.dlang.org/post/nepm2k$311l$1@digitalmars.com

Ping @schveiguy

**Comment by schveiguy** [comment]
I don't know if inout is something that needs to be in "first 5 minutes" :) If so, I can try and put something together.

Regarding the (inout int = 0) crap, that's just a bug that needs fixing.

**Comment by wilzbach** [comment]
> I don't know if inout is something that needs to be in "first 5 minutes"

Currently the tour is divided in two parts - the basics that depend on each other and are thought to be simple - those are targetting the "first 5 minutes" and gems which highlight advanced features in D and imho `inout` is one of those advanced features.

Atm I am not sure where to put `inout` - maybe 
- [Attributes](http://tour.dlang.io/tour/gems/10)
- [Storage classes](http://tour.dlang.io/tour/basics/4)
- new gem

@stonemaster do you have a good idea?

**Comment by schveiguy** [comment]
I need to take a closer look at how it's organized. Added to plate ;)

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#21
