### ISSUE TITLE
copy download page for "Install locally"

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#148]
http://dlang.org/download.html

looks a lot nicer than

http://tour.dlang.io/tour/welcome/2

Imho we should copy most of it - at least having images is nice :)

**Comment by stonemaster** [comment]
I think I wouldn't want to copy that page (I agree it looks nice) but that would mean having HTML layout and tables and such which is a pain for translation. Maybe there is another way to restructure things..

**Comment by wilzbach** [comment]
> I think I wouldn't want to copy that page (I agree it looks nice) but that would mean having HTML layout 

Fair enough, maybe we go step by step and just introduce the nice icons?

**Comment by stonemaster** [comment]
Starting with icons is a good idea

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#46
