### ISSUE TITLE
Push a notice to dlang.org after first milestone

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#15]
Your dlang tour already looks great, there are a couple of small issues, but you definitely should get this public soon! This is great!

**Comment by stonemaster** [comment]
Posted on mailing list: http://forum.dlang.org/post/vylvnkpdjefmuvmqtdkn@forum.dlang.org

**Comment by wilzbach** [comment]
Great - I also meant dlang.org - see [this PR](https://github.com/dlang/dlang.org/pull/1302)
