### ISSUE TITLE
Building/linking libraries (static / dynamic)

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#151]
- how to create a static,dyn library using dmd
- how to link a static, dyn library using dmd

another often asked topic is how to create dll's.

**Comment by stonemaster** [comment]
This is a topic which I see being described on the official dlang site or a blog post. It's not something you can do in an online tour after all.

**Comment by wilzbach** [comment]
Makes sense. I think there is even something on dlang.org, should we link to this somewhere?

**Comment by stonemaster** [comment]
I think it could be mentioned in a #150 gem. But currently we don't have a good fit for something like that.
