### ISSUE TITLE
show somehow that the memoization works

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#181]
would be quite cool if we could get a debug statement into the function that prints to stdout, to show that the function is really only called once.

http://tour.dlang.io/tour/gems/7

**Comment by stonemaster** [comment]
That will be difficult because the nature of `pure` functions is to not change any other state.

**Comment by wilzbach** [comment]
They allow to have debug statements, but then rdmd would need to be run with `-debug`

**Comment by stonemaster** [comment]
Has `-debug` any other issues e.g. changes behaviour of imported standard modules?

**Comment by wilzbach** [comment]
As a disclaimer: I am not an expert on this though. 

It runs all debug blocks , but phobos is already compiled so afaict no. Moreover  there are only a handful statements in Phobos. 

btw you should probably also activate `-g` (symbols) for a more pleasant stack trace.

**Comment by ZombineDev** [comment]
`-debug` is the default anyway, so no need to worry.

**Comment by stonemaster** [comment]
Closed with #194
