### ISSUE TITLE
don't use number is the url - use the slugified title

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#184]
e.g. instead of

http://tour.dlang.io/tour/basics/3

-> 

http://tour.dlang.io/tour/basics/memory

**Comment by stonemaster** [comment]
Either this one or #137 otherwise it will be hard to maintain an organised file structure.

**Comment by wilzbach** [comment]
Closed in favor of #137

**Comment by stonemaster** [comment]
I think using your idea from #137 we'll be able have both. It will be just the .md file's title after XX_. We won't have a translated title but I think will be okay. Easier than the numbers.

**Comment by wilzbach** [comment]
solved by #224 :)
