### ISSUE TITLE
mention asm.dlang.org somewhere

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#185]
http://asm.dlang.org is a great service and we should mention this - maybe related with #128.

Ping @ibuclaw

**Comment by stonemaster** [comment]
There currently no section where this fits in. A link in the welcome link list would currently be the natural choice.

**Comment by wilzbach** [comment]
I plan to write a short gem about inline assembler and then we can link it there. 
It's a very specialized tool that requires some rough understanding of assembler, so I would hide from the newcomers.

**Comment by stonemaster** [comment]
Okay then let's close this one and have it mentioned in the inline asm gem. Good idea!
