### ISSUE TITLE
guide to CI integration

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#186]
for travis it's quite simple - thanks to @MartinNowak 
and in it's simplest version is just

```
language: d
```

For other linux CIs one can use MartinNowak's install script or download dmd/dub manually.

Windows is possible too, but currently [a bit more complicated](https://github.com/libmir/mir/blob/master/appveyor.yml). However I heard that @MartinNowak is working on an official Windows install script?

**Comment by stonemaster** [comment]
I am really unsure that this fits to the tour. It's not something that can be tried out online in any way. I think something like that is better be written down in an external blog article.

**Comment by wilzbach** [comment]
makes sense - imho the best is to put it on dlang.org, s.t. it is updated from time to time. Do you mind if I keep this open until I made a PR there?

**Comment by stonemaster** [comment]
Yup no problem

**Comment by wilzbach** [comment]
It's now part of the D wiki https://wiki.dlang.org/Continuous_Integration ;-)
