### ISSUE TITLE
confusing end of welcome chapter

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#187]
> Could you point out why it is confusing to you.

I had the same experience. The page number is 5/5 and the arrows are grayed out. That looks like "the end" to me.

> Currently the text says:
>
> "Either use the navigation panel at the bottom or press the right arrow
> key."

But before that, it says "Congratulations for finishing the first chapter. You're now ready to dive into the world of D." which may (and did to me) mean "this is the end, go out there and try out D now." It's easy to miss "first chapter" in there.

> What could we add to avoid the confusion?

1) Arrows should not be gray (how about green?)

2) 5/5 doesn't carry much meaning for me and potentially confusing as it did

**Comment by wilzbach** [comment]
3) Add more text about the next chapter e.g.

"In the next chapter you will learn about  the basics about D"

**Comment by stonemaster** [comment]
> 1) Arrows should not be gray (how about green?)
I think green won't fit in the overall colour scheme. But I do agree that gray might not have been the optimal choice. Maybe some tone of D's red might help already.

> 2) 5/5 doesn't carry much meaning for me and potentially confusing as it did

We could just drop that information altogether? It's something taken as "inspiration" from the Go tour.

> 3) Add more text about the next chapter e.g.
> "In the next chapter you will learn about the basics about D"

There is already the next/previous chapter's title near the arrows. I don't that this is needed as it will just create more visual noise. But maybe display could be organised to it clearer that the arrows have the purpose to navigate.

**Comment by wilzbach** [comment]
> We could just drop that information altogether? It's something taken as "inspiration" from the Go tour.

I think structure and showing where exactly you are is great, but maybe we can find a better way?
e.g. #201
That being said we can at least drop the (ugly) numbers for now?

> 3) Add more text about the next chapter e.g.

The idea was to put this into fulltext.

**Comment by wilzbach** [comment]
btw related to #40 ;-)

**Comment by wilzbach** [comment]
idea: maybe we can just use a slim 1px progress line for each chapter?  (instead of displaying the numbers)

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#45
