### ISSUE TITLE
Cache program output

### ISSUE THREAD

**Issue by greenify** [stonemaster/dlang-tour#19]
As we don't allow networking or file writes, pretty much anything could be cached. We might of course search for exception (e.g. time if we can't fix this like on the GoTour, see below). The reason for this is obvious, most of the time the user directly click on run without changing the file, so spawning a new docker container and compiling the file just takes unnecessary time. 

Btw citing from the GoTour.

> In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.

**Comment by stonemaster** [comment]
There already is a caching algorithm implemented for this purpose. I creates a hash of the source code and checks whether we already have compiled and run the example. But still, I'll leave this issue open because it is just a quick hack and should be re-visited and reviewed before a final release.
