### ISSUE TITLE
exceptions not mentioned

### ISSUE THREAD

**Issue by aG0aep6G** [stonemaster/dlang-tour#211]
Coming from <https://issues.dlang.org/show_bug.cgi?id=16121>, I've noticed that the tour doesn't mention exceptions. Should be in the basics, I think.

**Comment by wilzbach** [comment]
See #265  ;-)

**Comment by wilzbach** [comment]
Exceptions have been added since a while: http://tour.dlang.org/tour/en/basics/exceptions

We are happy about improvements ;-)
