### ISSUE TITLE
start to analyze google analytics

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#213]
At some point, we should start to get some insights for Google Analytics - ideas:

- how long a person stays on each page (maybe a metric for bad pages)
- on what pages a user bounces
- ...

**Comment by JackStouffer** [comment]
Yeah, that way we can guess on where pages have difficulty spikes that turn people away.

**Comment by wilzbach** [comment]
Thanks @stonemaster for giving me access to Google Analytics. I had an initial look to those pages and opened some issues based on a short analysis. I am pretty sure we can gain more insights - @JackStouffer please ping @stonemaster via mail for access.

Anyway let me start with the good news we had more than 2.5K (and 16.5K views) users within the last 30 days. Dlang.org has about 300K visit (subtract the bots and regular documentation users from this).
So the Dlang Tour is clearly gaining importance! :)

![image](https://cloud.githubusercontent.com/assets/4370550/15973805/98df7a9c-2f45-11e6-96c8-f7880b5602ba.png)

I am guessing @CyberShadow is also interested in such statistics ;-)

**Comment by wilzbach** [comment]
closing this as the first round of analysis gave us quite a lot of information. If someone wants to have access to GA, please ping @stonemaster privately ;-)
