### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#215]
From the forum:

Error pages are not styled for the tour (http://tour.dlang.org/). So, for example, if instead of writing the following currently valid URL "http://tour.dlang.org/" I type "http://tour.dlang.org//", it gives me a "ugly" 404 error page. That can be definitely improved.

Not only, and this is even more "critical" for new users. If I type "https://dlang.org//asdasd" instead of "https://dlang.org/", the server returns us a "ugly" 404 error page.

**Comment by stonemaster** [comment]
Good point and should be quite easy to do with vibe.d.
