### ISSUE TITLE
show download instructions based on OS

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#246]
- will help to clean-up the huge mess on page 2
- for false-positives we can have a small button "show all"

Also using nice icons (eye candy), might increase the user flux.

**Comment by stonemaster** [comment]
I'd rather favor a clean download page which makes clear what to do for each platform. Otherwise we end up having logic in the content..

**Comment by wilzbach** [comment]
Well it could be done via Javascript that operates on div ids, but I agree that this feature is controversial.

**Comment by wilzbach** [comment]
FYI: there has been a recent PR at dlang.org that adds this OS detection to the frontpage

https://github.com/dlang/dlang.org/pull/1437

Maybe we could use our new macro tags to separate the logic from the content?

**Comment by ZombineDev** [comment]
Yes, but as far I understand, the detection still has to be done via JS? Though, I'm not familiar with macro tags. Where can I read more, see examples, etc. ?

**Comment by wilzbach** [comment]
It had been developed very recently, but this

https://github.com/stonemaster/dlang-tour/blob/master/CONTRIBUTING.md#custom-mustache-macros

Is probably the best place

**Comment by stonemaster** [comment]
Have a look at https://github.com/stonemaster/dlang-tour/blob/master/CONTRIBUTING.md and the *Custom Mustache macro* section

**Comment by ZombineDev** [comment]
Thanks for the pointers.

**Comment by MartinNowak** [comment]
Also please see our point from the [First 5 minutes](https://trello.com/c/g8ahgOdf/202-first-5-minutes) session.

> First steps shouldn't be about compiling b/c you can just run the examples in the browser. Installation should be handled by dlang.org, maybe just append a transition from the tour to using D on your own machine.

From our perspective it would make more sense to just have a small hint (link to download page) on how to install a D compiler. But of course dlang's download page leaves open many questions that you're trying to address in [Install D locally](http://tour.dlang.org/tour/en/welcome/install-d-locally).
What we need for dlang is a good landing page after downloading something.
We still have the old platform pages, e.g. [DMD Compiler for Linux](https://dlang.org/dmd-linux.html), but they're a mess.

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#60
