### ISSUE TITLE
Add how-to about running the tour offline 

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#260]
As in the go tour, we could have a short page or subpage in the first pages that explains how to run the tour via dub. 

Follow-up to #250

**Comment by stonemaster** [comment]
Dependency: #137

**Comment by wilzbach** [comment]
@stonemaster afaict you need to release new git versions once you fixed something - `dub` will download the latest version automatically, not the latest git version.
There is also `dub fetch dlang-tour --version="~master"`, but I am not sure whether we should recommend this command.

**Comment by wilzbach** [comment]
Just bumping this. Basically we only need to decide whether we advertise the use of `--version="~master"` (imho it does make sense because for now it saves us a release process and our latest, greatest content is on "master").

... and then put the commands on the welcome pages:

```
dub fetch dlang-tour  --version="~master"
dub run dlang-tour
```

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#55
