### ISSUE TITLE
D Playground 

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#268]
I just came across Apple's announcement of their Swift playground. 

http://www.theverge.com/2016/6/13/11924120/apple-swift-playground-app-teaches-kids-to-code

Maybe we can learn a bit from this?

**Comment by ZombineDev** [comment]
Apple's playground is just a very poor implementation of Bret Victor's ideas. See [this](http://worrydream.com/LearnableProgramming/) for the source of truth ;)

**Comment by stonemaster** [comment]
The dlang tour is more aimed towards advanced programmers and I think it should stay that way. There are a lot of womderful resources out there that teach programming and I think the tour should concretate on what makes D a very good language compared to others.

**Comment by wilzbach** [comment]
@stonemaster understood - it was more a ping that there are many ways to make guides visually appealing and more interesting, but I guess we have a lot of other stuff on our roadmap and thanks to Google analytics  we know that we need to make our intro  pages more interesting ;-)
As those are separate issues, closing this one. Sorry for the noise.
