### ISSUE TITLE
Add random delay when program output is cached

### ISSUE THREAD

**Issue by stonemaster** [stonemaster/dlang-tour#28]
Instead of directly returning cache contents, add small 500ms-2s delay. This keeps user from suspecting weird stuff.

**Comment by wilzbach** [comment]
Is this done similar for the gotour?

**Comment by stonemaster** [comment]
I don't know how the gotour does it :-) The dlang-tour doesn't have restrictions imposed regarding random numbers or the timezone as the online code is just run within a container. That of course means that once cached those values are output again. This feature is just about adding a random delay before returning output to the user to make the output *seem* to be real-time.
