### ISSUE TITLE
Code editor doesn't adapt size to source code

### ISSUE THREAD

**Issue by stonemaster** [stonemaster/dlang-tour#283]
Probably starting with killing off Bootstrap the code editor doesn't resize automatically to the height of the screen which now looks akward:

![tour-code-editor](https://cloud.githubusercontent.com/assets/1463490/16071401/750c034e-32db-11e6-81c2-5bbb33fb682c.png)

Before there was a style set that makes code mirror always take as much space as possible.

**Comment by wilzbach** [comment]
That's interesting - it never looked different to me. 
What browser are you using?

**Comment by stonemaster** [comment]
That was Chrome. I tried the same page with Firefox and it looks the same. It looks different only for source code that is long enough to span multiple "pages". I think I added a CSS attribute ` height: auto` for the editor or something like that..

**Comment by stonemaster** [comment]
The `viewportMargin` it is: https://codemirror.net/demo/resize.html
