### ISSUE TITLE
Pages keep changing randomly on Android

### ISSUE THREAD

**Issue by joakim-noah** [stonemaster/dlang-tour#285]
I've been going through the tour on my Android tablet, and until recently, it was all fine.  Something changed today, however, and the tour is now unusable on my Android tablet and phone.  Any time I scroll the page, it will randomly reload or move to the previous or next page in the tour, not sure why.  Please fix.

**Comment by wilzbach** [comment]
That sounds weird, but it's probably due to the swiping support.  I will disable it until we find out the cause. 
Thanks for reporting!

**Comment by joakim-noah** [comment]
That fixed it, had to reload the js file, but back to normal now.
