### ISSUE TITLE
enable gzip support

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#293]

**Comment by stonemaster** [comment]
Vibe.d is configured to already use gzip support: https://github.com/stonemaster/dlang-tour/blob/master/source/app.d#L114

If this doesn't do what it's supposed to we need to do our own compression somehow (ugly)

**Comment by JackStouffer** [comment]
@stonemaster Is vibe.d behind a nginx or apache server? If so, just enable it there.

**Comment by stonemaster** [comment]
@JackStouffer No vibe.d is used directly without reverse proxy. And I prefer to have it that way to simplify container deployment.

**Comment by JackStouffer** [comment]
Digging into this a bit more, I realized that the two CSS files that were not gziped are font awesome and the font files from google. As these are out of your control I think this can be closed.

**Comment by stonemaster** [comment]
Looking at the developer tools I can see that the tour correctly responds with gzip compressed content when the clients asks to. Closing.
