### ISSUE TITLE
Take inspiration from tours of other languages 

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#30]
Hey I accidentally came by a couple of such tours or schools, lately and I thought I post this list here as a starting point for inspiration and further ideas. Have fun browsing. 

http://rustbyexample.com/
http://twitter.github.io/scala_school/
https://tour.golang.org/
http://nodeschool.io/
https://phpschool.io/
http://tryruby.org/

**Comment by stonemaster** [comment]
I am closing this one. I did the Go tour some time ago and had a look at the Rust tour. I will just rely on users to bring in some concrete ideas on what to improve on the tour :-)
