### ISSUE TITLE
Agreement that tour contents in English meet overall expectations and next round of reviewing has passed.

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#339]
@stonemaster maybe you can create a translation milestone and add this + #55 to it?

**Comment by wilzbach** [comment]
Imho the content is in a good shape and we will only issues in the best way when we have a detailed look at it (= starting translating).

@stonemaster I have started writing up a small guide for the other translators of my experience at

https://github.com/stonemaster/dlang-tour/wiki/Tips-for-translators

And written a small tool that automates submitting multiple PRs:

https://github.com/wilzbach/splitup-prs

(It's not perfect, but it already saves time for me)

- Once you give your okay I would close this issue and ping our motivated translators with the experience I made with the start of the German tour.
- We still need to translate some UI elements (e.g. "Run", but I think that relatively minor and can be done very quickly)
- I would also wait from your experience when reviewing the PRs - e.g. 
  - what does it make hard/easy to review
  - what is a typical list of mistakes

=> let's get the party started :tada:

**Comment by stonemaster** [comment]
Thanks a lot for your and the guide! :+1: I really like it. I am totally
fine with closing this. Anythinf will be fixed with Mord visitors and time.

**Comment by wilzbach** [comment]
> Thanks a lot for your and the guide! :+1: I really like it. 

Awesome. Will do :)

**Comment by wilzbach** [comment]
Opened the competition at #132
