### ISSUE TITLE
FF doesn't use syntax highlighting for codeblocks

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#345]
e.g. http://tour.dlang.io/tour/en/basics/memory

![image](https://cloud.githubusercontent.com/assets/4370550/16332642/5ac95fc2-39f7-11e6-9194-c8078f4277c5.png)

**Comment by stonemaster** [comment]
I can confirm the issue on Safari/Mac too.

**Comment by wilzbach** [comment]
fixed with #453
