### ISSUE TITLE
move over to official dlang repo

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#36]
probably makes sense to move it over to dlang, s.t. other people can help to maintain this and it's gets visibility and an official status.
Ping @CyberShadow

**Comment by CyberShadow** [comment]
I think we generally do that when the bus factor exceeds critical mass for continued existence, but also AFAIK the location of the actual git repository has little importance.

Perhaps we should start by linking to the tour from the "Learn" link in the navigation bar, which currently leads to a rather minimal page.

**Comment by stonemaster** [comment]
@CyberShadow That's a nice idea.

**Comment by wilzbach** [comment]
@CyberShadow I didn't know that the D Foundation sponsors the server for the tour. Your statement still makes sense, but imho as long as it has the official subdomain, it would be nice if it was also part of the official github namespace ;-)
Btw @stonemaster is it possible to give people like @CyberShadow (emergency) access to the server?

**Comment by stonemaster** [comment]
@CyberShadow  I got the credentials from Jan Knepper who also seems to manage other dlang related servers. Just approach to him if you would like to have access to this box. For me it totally makes sense to have more people being able to help if it burns :-)

**Comment by stonemaster** [comment]
This is not really a content/tour issue. When the tour has gained enough backup in the community this will be a step that just happens naturally. I already told Andrei that I am totally fine with transferring ownership to the D foundation.

**Comment by wilzbach** [comment]
> I think we generally do that when the bus factor exceeds critical mass for continued existence, but also AFAIK the location of the actual git repository has little importance.

@CyberShadow Is nearly 3K visitors in the first month and  ~300 issues enough?

**Comment by JackStouffer** [comment]
I think visibility wise it's a good idea, it's up to @stonemaster though if he wants to or not.

**Comment by CyberShadow** [comment]
Don't ask me, ask W/A.

**Comment by stonemaster** [comment]
I am okay with moving this to the official repos. I already told Andrei so.

**Comment by stonemaster** [comment]
But again I follow @CyberShadow's argument: I doesn't really matter where there repository is located. People will start using the tour and hopefully like it and after some time the integration will come naturally.

**Comment by andralex** [comment]
Let's give it a couple more months. Thanks!

**Comment by wilzbach** [comment]
> I think visibility wise it's a good idea, it's up to @stonemaster though if he wants to or not.

@stonemaster I am thinking about using git submodules for the languages, s.t. we can setup teams for every language and they have full access to their files. In any case I went ahead and created the organization `dlang-tour` and invited you and @ZombineDev to it.

https://github.com/dlang-tour

Regardless of using git submodules, what's your opinion about using `dlang-tour/tour`, `dlang-tour/master`  or `dlang-tour/stone` for the main repo?

**Comment by wilzbach** [comment]
I close this as the `dlang-tour` organization has been working well so far -> I am closing this.
In case anyone wants/needs access, please ping us.
