### ISSUE TITLE
state motivation for gems/unittesting

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#364]
more example here of testing. why we should do it. dlang idioms of do it.

(reported by @claudiug)

**Comment by stonemaster** [comment]
I don't think we have to give a motivation on why unit testing  is good thing. It's common knowledge in software development since some years that unit testing leads to a higher software quality and reduces the risk of regressions. We should focus on what D brings to make unit testing easier.

**Comment by claudiug** [comment]
@stonemaster agree with you. when you doing rails, you have to do test, you become a compiler  😄 

will be great to show dlang way of doing test, and some examples

**Comment by wilzbach** [comment]
> I don't think we have to give a motivation on why unit testing is good thing. It's common knowledge in software development since some years that unit testing leads to a higher software quality and reduces the risk of regressions. We should focus on what D brings to make unit testing easier.

#369 contains a one-liner intro (you may call that motivation). 
Feel free to nitpick that PR ;-)
