### ISSUE TITLE
more detailed gems/contract-programming

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#365]
found this chapter quite nice. but will be nice to have more details

(reported by @claudiug)

**Comment by wilzbach** [comment]
#342 is a recent addition that adds a bit more content to gems/contracts chapter. What else do you miss?

**Comment by stonemaster** [comment]
I would like here to stress the point that dlang-tour is a "tour" of the language and not _the_ reference on all topics of the D language. If the reader gets some idea of the language and thinks it's a nice feature - we still have links that explain the language features in much more detail.

**Comment by claudiug** [comment]
@stonemaster I tend to disagree here. As is quite a nice and unique feature of dlang, maybe should be promoted 😄

**Comment by stonemaster** [comment]
@claudiug Yes you are definitely right. That's one of the great features of D that have never seen anywhere else. So you're invited to have a look at #342 then whether it's get more weight as it deserves :-)

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#35
