### ISSUE TITLE
syntax highlighting for D

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#38]
- for markdown you could use https://highlightjs.org (they support D) (content just needs the "d" class) and you can build a custom package ;-)
- codemirror supports D out-of-the-box: http://www.cs.princeton.edu/~dp6/CodeMirror/mode/d/index.html

**Comment by stonemaster** [comment]
That's weird. Codemirror should be configured to use D already. And markdown highlighting should have been working some ago using google's codeprettify. Will have a look at this.
