### ISSUE TITLE
Typo (foreach)

### ISSUE THREAD

**Issue by dmi7ry** [stonemaster/dlang-tour#382]
http://tour.dlang.org/tour/en/basics/foreach

    foreach (e; arr) {
        // typoef(e) is int
        writeln(e);
    }

typoef -> typeof

**Comment by wilzbach** [comment]
Thanks, for reporting  @dmi7ry, do you want to  press on edit (directly on the page) and change it yourself?

**Comment by dmi7ry** [comment]
https://github.com/stonemaster/dlang-tour/pull/383

**Comment by wilzbach** [comment]
Thanks again.
