### ISSUE TITLE
a lot of whitespace at the footer

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#39]
![image](https://cloud.githubusercontent.com/assets/4370550/15226143/2b3dcd4e-188a-11e6-904b-e0e4165592e4.png)

just a nitpick, but probably easy to remove this space.

**Comment by stonemaster** [comment]
Do you mean the space between "Keyboard shortcuts" and the browser's bottom page?

**Comment by wilzbach** [comment]
Yes it feels unnecessary
