### ISSUE TITLE
different theming than dlang.org

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#42]
![image](https://cloud.githubusercontent.com/assets/4370550/15226650/47ed54d0-188c-11e6-994f-0109572d0805.png)

compared with:

![image](https://cloud.githubusercontent.com/assets/4370550/15226659/5202cf2c-188c-11e6-9b15-1953fbdecf2a.png)

I actually separated the `menu` from the other JS on dlang.org, so it should be easy to use.
See e.g.

https://github.com/dlang/dub-registry/blob/master/views/layout.dt

https://github.com/dlang/dub-registry/blob/master/public/scripts/menu.js

and https://github.com/dlang/dub-registry/tree/master/public/styles

**Comment by stonemaster** [comment]
I think that can be be closed, right?

**Comment by wilzbach** [comment]
I would wait for #253 as the heading and code boxes are still different.

**Comment by stonemaster** [comment]
#253 has been merge so closing this one
