### ISSUE TITLE
Review usage of "you"

### ISSUE THREAD

**Issue by ZombineDev** [stonemaster/dlang-tour#423]
`cd public/content/ && grep -Hnr "you"` yields:

- [ ] en/basics/further-reading.md:3:Now that you've finished the basics, you can move on to some more advanced sections of this tour. Or, you can check out some of the following resources:
- [ ] en/basics/further-reading.md:20:* Share your ideas in the [Forum](https://forum.dlang.org/) or scan very active discussions
- [ ] en/basics/imports-and-modules.md:3:To write a simple hello world program in D you need
- [ ] en/basics/memory.md:3:D is a system programming language and thus allows you to manually
- [ ] en/basics/memory.md:4:manage and mess up your memory. Nevertheless, D uses a
- [ ] en/basics/ranges.md:36:Don't fool yourself into deleting the `assert`ions!
- [ ] en/basics/storage-classes.md:6:at compile time.  Good type-safety gives you the support you need
- [ ] en/basics/storage-classes.md:32:is `const` for your current scope, but someone
- [ ] en/basics/storage-classes.md:34:you will be sure that an object's value will never
- [ ] en/basics/structs.md:63:member function can be used you to work to give access to all instances of a
- [ ] en/gems/bit-manipulation.md:61:Hence in D `std.bitmanip` helps you to write maintainable, easy-to-read bit manipulationsen/gems/bit-manipulation.md:73:OS memory layout (`size_t.sizeof`) e.g. `bool`, `byte`, `char`, it is recommended
- [ ] en/gems/documentation.md:7:out of your source code.
- [ ] en/gems/range-algorithms.md:9:The great thing with these algorithms is that you just
- [ ] en/gems/range-algorithms.md:10:have to define your own range and you will directly
- [ ] en/gems/range-algorithms.md:56:### The documentation is awaiting your visit!
- [ ] en/gems/range-algorithms.md:77:    string text = q{This tour will give you an
- [ ] en/gems/template-meta-programming.md:3:If you ever got in touch with *template meta programming*
- [ ] en/gems/template-meta-programming.md:4:in C++ you will be relieved what tools D offers to make
- [ ] en/gems/template-meta-programming.md:5:your life easier. Template meta programming is a technique
- [ ] en/gems/template-meta-programming.md:36:Anywhere you see *boiler plate*, `mixin template`
- [ ] en/gems/template-meta-programming.md:37:is your friend:
- [ ] en/gems/template-meta-programming.md:48:pre-processor if you're coming from C!
- [ ] en/gems/traits.md:51:A common problem is that in contrast to arrays you might not know the exact length
- [ ] en/gems/unittesting.md:103:// to actually test your modules.
- [ ] en/multithreading/message-passing.md:4:yourself D allows to use *message passing* as a means
- [ ] en/multithreading/std-parallelism.md:20:working threads. Creating your own instance allows
- [ ] en/vibed/basics-asynchronous-i-o.md:40:asynchronous socket operations so you don't have
- [ ] en/vibed/basics-asynchronous-i-o.md:42:blocks your whole application.
- [ ] en/vibed/database-connectivity.md:4:in your backend services. **MongoDB** and **Redis**
- [ ] en/vibed/deploy-on-heroku.md:39:This provides access to the Heroku Command-Line Interface (CLI), which can be used for managing and scaling your applications and add-ons.
- [ ] en/vibed/deploy-on-heroku.md:92:It is possible to use GDC or LDC and to choose a specific compiler versions by adding a `.d-compiler` file to your project.
- [ ] en/vibed/deploy-on-heroku.md:99:Proceed in your usual git habit and write awesome code.
- [ ] en/vibed/deploy-on-heroku.md:170:Heroku treats logs as streams of time-ordered events aggregated from the output streams of all your app and Heroku components,
- [ ] en/vibed/deploy-on-heroku.md:180:After deploying the app to Heroku you can make it more awesome by using add-ons. For example :
- [ ] en/vibed/vibe-d-web-framework.md:12:  for you! See the next section for a thorough
- [ ] en/vibed/vibe-d-web-framework.md:33:available for building your vibe.d based project.
- [ ] en/welcome/install-d-locally.md:21:To quickly install dmd within your user directory, run: `curl -fsS https://dlang.org/install.sh | bash -s dmd`
- [ ] en/welcome/links-documentation.md:3:After you complete the tour, you can check out some of the following links for help or more information:
- [ ] en/welcome/welcome-to-d.md:7:This tour will give you an overview of this __powerful__ and __expressive__

**Comment by wilzbach** [comment]
While i think the first one is valid, the others slipped in?

```
>  grep -Hnr " we "
en/welcome/welcome-to-d.md:46:and we are glad about pull requests making this tour even better.
en/vibed/basics-asynchronous-i-o.md:19:every time a call to socket would block - because we don't
en/vibed/basics-asynchronous-i-o.md:23:operation. When the data is available we just
en/vibed/basics-asynchronous-i-o.md:28:    // we return here.
en/vibed/json-rest-interface.md:4:If we want to implement the following JSON output for
en/vibed/json-rest-interface.md:44:To actual fill the data structures, we have to inherit
en/vibed/json-rest-interface.md:53:Given an `URLRouter` instance we register
en/basics/alias-strings.md:3:Now that we know what arrays are, have gotten in touch of `immutable`
en/basics/structs.md:73:which we will see in a future section.
en/basics/structs.md:143:    // Thanks to toString() we can now just
en/basics/ranges.md:78:    // But we do want to touch all elements and
en/basics/delegates.md:99:    // we can ensure that the switch covers
en/basics/slices.md:53:call a sub-slice is taken thus we don't
en/basics/functions.md:94:    // Depending on the result we call one of
en/basics/arrays.md:113:    // Make sure we the algorithm works
en/gems/template-meta-programming.md:101:    /// we really hate boiler plate!
en/gems/template-meta-programming.md:143:    // we statically enabled it only for float's
en/gems/contract-programming.md:121:        // verify we return YYYY-MM-DD
en/gems/compile-time-function-evaluation-ctfe.md:59:    // approximation because we think the change
en/gems/range-algorithms.md:99:      // we don't need duplication, right?
en/multithreading/std-parallelism.md:120:    // Get our result we sent to background
en/multithreading/message-passing.md:133:    // And we wait until all threads have
```

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#32
