### ISSUE TITLE
Convert comments on function examples to /** */ style

### ISSUE THREAD

**Issue by stonemaster** [stonemaster/dlang-tour#43]
As phobos does it all comments should have the `/**` and `*/` syntax for comments.

**Comment by wilzbach** [comment]
There are also a couple of other Phobos style guidelines - like Allman braces Or spaces between import selections etc that we should look for and be consistent. Ideally we should run Dscanner on our code samples.

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#47
