### ISSUE TITLE
Mobile-friendly/responsive view 

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#44]
After having had a look at the Go and Rust tour, which are both nice to read on one's phone - I think we can do a better than this 

![screenshot_20160513-100120](https://cloud.githubusercontent.com/assets/4370550/15240374/db9cd510-18f1-11e6-8c35-95d3b008715e.png)

Some ideas
- move the example code below the text on mobile 
- use the responsive dlang.org menu 
-...

**Comment by stonemaster** [comment]
Bootstrap is used for theming so bascially this should work with some tweaking. On my phone (HTC One X+) and on my Ipad Mini the tour looks good in horizontal setup at least. I think the column tags must be set appropriately somehow.

**Comment by wilzbach** [comment]
> Bootstrap is used for theming so bascially this should work with some tweaking. 

Hmm maybe you need to set the viewport correctly?
At least I expected the content to wrap, s.t. on mobile I only read the text and the example code is at the bottom of the page:

![image](https://cloud.githubusercontent.com/assets/4370550/15479235/7d6aa8ec-211f-11e6-9b65-3e072740b7f9.png)
