### ISSUE TITLE
Merging out-of-date user PRs without admin rights

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#440]
If the branch is not on `dlang-tour` contributors without admin rights can't update it, so only @stonemaster could merge such PRs. As we hopefully will get a bunch of PRs (we specifically asked for it), the restriction that the branch needs to be up-to-date with the `master` branch seems a bit annoying.

![image](https://cloud.githubusercontent.com/assets/4370550/17651887/f49f23d4-626f-11e6-9994-5f3637abfb53.png)

Proposed action:
@stonemaster could you please toggle the setting "Require branches to be up to date before merging" off? I think we are pretty safe if it passed on Travis once and this requirement is really pure annoyance for now :/
(screenshot is from a different repo as collaborators can't access the settings)

![image](https://cloud.githubusercontent.com/assets/4370550/17651903/9b40e68c-6270-11e6-9965-3594b3ac4a0b.png)

**Comment by stonemaster** [comment]
AS long as there are no conflicts this option doesn't speed us exactly :-) turned of now.

**Comment by wilzbach** [comment]
Thanks a lot!

> AS long as there are no conflicts this option doesn't speed us exactly :-) turned of now.

Well if there's a real conflict, we (as contributors) can't do anything about it anyways, because the CI still has to pass and thus we can't do local merges ;-)
