### ISSUE TITLE
Close button not displayed correctly in Chrome/Linux

### ISSUE THREAD

**Issue by stonemaster** [stonemaster/dlang-tour#447]
The close button in the UI isn't displayed correctly in Chrome/Linux:

![dlang-tour-close-button](https://cloud.githubusercontent.com/assets/1463490/17693620/178ab63e-63a0-11e6-893d-9b5e218125ef.png)

**Comment by wilzbach** [comment]
that's funny in my Chrome & chromium it looks correct:

![image](https://cloud.githubusercontent.com/assets/4370550/17757285/c381fd9e-64e5-11e6-802d-9c015f633049.png)


but my Firefox shows the same problem - will dig into it.

**Comment by wilzbach** [comment]
This should have been closed automatically :/
