### ISSUE TITLE
Use SSL

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#45]
It seems to be a general trend to use ssl and nowadays Google puts that into their ranking too. Thanks to the letsencrypt project we can have ssl for free :)

**Comment by stonemaster** [comment]
Yes we should do that definitely. Should be quite easy with lets encrypt.

**Comment by nazriel** [comment]
There are planty scripts on web that can make it even easier.

Just one thing to remember: you have to make sure to add some cronjob or something to renew the certificate for you. Letsencrypt creates certificates valid only for three months AFAIK

**Comment by stonemaster** [comment]
@nazriel Thanks for the hint. I once setup lets encrypt for my private server but the trick with crontab is a great idea.

**Comment by wilzbach** [comment]
@stonemaster let me know if you need help, I have used let's encrypt quite often recently.
