### ISSUE TITLE
make SSL the default

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#450]
As Google will [actively downrate](http://motherboard.vice.com/read/google-will-soon-shame-all-websites-that-are-unencrypted-chrome-https) us if we still serve requests over HTTP, how about redirecting all HTTP reqeusts to HTTPs by default (if SSL is configured)?

**Comment by stonemaster** [comment]
This sounds like a reasonable thing. We just have to make sure to still allow local developers to work without an certificate i.e there should be switch that enables that behaviour. In our production docker container will be turn that on by default but locally we won't.
