### ISSUE TITLE
are markdown tables supported?

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#46]
Could be quite useful for e.g. the basic types as

type | size | default value
------|--------|------------------
int   | 32bit | 0

**Comment by stonemaster** [comment]
Markdown is rendered through vibe.d so it depends on that implementation. But it would be nice to have this supported.

**Comment by stonemaster** [comment]
Opened an issue in vibe.d: https://github.com/rejectedsoftware/vibe.d/issues/1493

**Comment by wilzbach** [comment]
hmm this page looks pretty ugly otherwise - how about just using plain-old HTML tags for the time being?

**Comment by stonemaster** [comment]
#156 made this issue redundant.
