### ISSUE TITLE
Trigger master builds on submodule events

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#460]
Some ideas:

1) Move deploy steps to `deploy.sh` and call in language repos

```
wget https://raw.githubusercontent.com/dlang-tour/base/master/deploy.sh
./deploy.sh
```

Problems: All language repos need to have the Docker Auth codes?

2) Restart the last master build from the language repo

https://github.com/MartinNowak/dlang-bot/blob/master/source/app.d#L409
https://docs.travis-ci.com/api#builds

- one can make a request to /builds/{build.id}/restart
- we could hast this as a d/dub/shell script in the base repo
- Problems:  All language repos need to have the Travis Auth Token

3) Heroku App with PR Hooks

- similar to 2), but without the need of exposing & copying the auth codes to every repo
- see https://github.com/MartinNowak/dlang-bot/blob/master/source/app.d for a start

I think 3) is the most flexible approach and with an 550h (=20 days) (or 1000h (=42 days) with verified CC), we should be able to run this for free as the app won't receive hooks all the time and gets idle after 15 mins. What do you think?

(part of #454)

**Comment by wilzbach** [comment]
> 3) Heroku App with PR Hooks

Turns out this option was easier than thought - I setup a free Heroku account, configured auto-deploy directly from the Github repo & sent invitation to @stonemaster and @ZombineDev just in case.

https://github.com/dlang-tour/bot

All language repos now have a hook to https://dtour-bot.herokuapp.com & the bot will trigger the last Travis build of this repo if a new PR has been merged, I already tested it with the spanish repo and the rebuild was successfully triggered :)
(in case you missed it, on a CI build this repo checks out the newest master version of all submodules)

-> I think that should get us going for now ;-)

**Comment by wilzbach** [comment]
Hmm while the rebuilds are working nicely and the new Docker images are built and sent to [DockerHub](https://hub.docker.com/r/stonemaster/dlang-tour/), the site doesn't update itself.

@stonemaster is there another hook in place or how does the automatic deployment get triggered?

**Comment by stonemaster** [comment]
Someelse then seems to be broken. The latest commit removing the keyboard shortcuts is live just right now. How the deployment works is documented in `DEPLOYMENT.md`. Basically a special container polls for updates in `stonemaster/dlang-tour:latest` and if the image ID changed exchanges the new container. So as long as we push to that Docker image tag nothing _should_ change :-)

**Comment by wilzbach** [comment]
>  Basically a special container polls for updates in stonemaster/dlang-tour:latest and if the image ID changed exchanges the new container. So as long as we push to that Docker image tag nothing should change :-)

That's how I understood it too - I only forgot that #465 wasn't in yet, so everything should be working now :)
