### ISSUE TITLE
Does the tour need line numbers?

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#475]
Just a silly question - do we need line numbers for our short snippets?
Some points:
- Usually they are between 10-25 lines
- We don't refer to a specific line number anymore
- Disabling line numbers saves space and reduces "visual noise" (especially good for mobile)
- Errors are already nicely mapped

Against:
- People maybe be used to having line numbers (I think for most editors the default is off?)
- For Runtime exceptions line numbers are shown
- ...

Here's a snippet with a bit more content and without line numbers:

![image](https://cloud.githubusercontent.com/assets/4370550/17994948/91d37808-6b5d-11e6-8a61-63f071cfa91c.png)

same with line numbers:

![image](https://cloud.githubusercontent.com/assets/4370550/17994960/a5fd7734-6b5d-11e6-8a9d-a4dafcc2dd14.png)

**Comment by ZombineDev** [comment]
Well, compiler error messages refer to line numbers, so it would quite tedious for the users to count the lines manually just to find out where the error is.

**Comment by ZombineDev** [comment]
Nevermind, I just saw the images, so I have no strong opinion for or against.

**Comment by wilzbach** [comment]
> Nevermind, I just saw the images, so I have no strong opinion for or against.

Me neither, we could also toggle the line number off for mobile devices only.

This is not really pressing & I assume @stonemaster has some thoughts we he enabled it?

**Comment by stonemaster** [comment]
I enabled them because it _was_ possible :-) And when coding I always have line numbers enabled. And if you have an error and will find the line quickly. But I am okay with removing if it has more benefits. Errors are also shown inline..

**Comment by wilzbach** [comment]
> And when coding I always have line numbers enabled. A

Of course the same is true for my Vim setup ;-)

> But I am okay with removing if it has more benefits.

Well the only benefit is less space / visual clutter.
Btw the Go Tour has line numbers enabled, whereas the Rust Tour doesn't show them. 

As said before I don't have a strong opinion on this topic, I just accidentally discovered that we could save space.

**Comment by stonemaster** [comment]
Because it is less work and no one has any strong arguments on removing them - I'll just close this issue. If there is need for a toggle or something like that we might re-open this one.
