### ISSUE TITLE
More links to API documention

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#48]
I think it would be nice if a method is mentioned that we provide links for the reader to deeper dive into the docs - they support anchors ;-)

I think just linking inline should be okay.
If possible a "Resources" list at the bottom (or "Dive deeper") would be cool too for a couple of pages.

**Comment by stonemaster** [comment]
Good idea.

**Comment by wilzbach** [comment]
This issue was moved to dlang-tour/english#17
