### ISSUE TITLE
A simple release cycle

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#482]
e.g every month

![image](https://cloud.githubusercontent.com/assets/4370550/18174797/21254278-706f-11e6-854c-cf157159d04a.png)

https://github.com/stonemaster/dlang-tour/compare/v1.0.1...v1.0.2

**Comment by wilzbach** [comment]
btw this is also related to our offline install instructions (https://github.com/dlang-tour/english/issues/55), if we release a minor or patch version from time to time, we don't have to advertise  `dub fetch dlang-tour --version="~master"`, but of course this is a bit of more work for us.

**Comment by stonemaster** [comment]
I would suggest not having a release cycle based system because this involves manual work.

Another question arises here: what happens when the user fetches dlang-tour via dub? Are submodules are fetched as well? And in which state are these submodules? I think there are at most at the checked in state which differs from the HEAD of each language repository? How can we prevent that?

**Comment by wilzbach** [comment]
> I would suggest not having a release cycle based system because this involves manual work.

Well, for example we had `dlang-tour` on DUB broken with 2.072 for the last two months, because there was no new release even though @ZombineDev quickly provided fixes.
I am also for a system that is less work, but the past shows that we tend to forget to release new versions.

> Another question arises here: what happens when the user fetches dlang-tour via dub? Are submodules are fetched as well? And in which state are these submodules? I think there are at most at the checked in state which differs from the HEAD of each language repository? 

Oh I just realized that `dub` >= 1.0.0 doesn't seem to checkout git submodules anymore - I am not sure, but I think that at some point in the past it did correctly checkout the submodules.
The current behavior of `dub` is to create empty folders for the submodules (as the git repository), but it is a mere copy of the repository without any `.git` information. IIIRC `dub` does nothing more than using the zip export on GitHub, which doesn't checkout the submodules either.

> How can we prevent that?

Note sure at the moment. Ideally we could tell `dub` to do the git submodules checkout for us (see e.g. [this issue](https://github.com/dlang/dub/issues/1044)).
A couple of ideas:
- A bootstrap D script that downloads the base tour and its translation repositories (DUB has an API interface)
- A hook script that checks whether the translation are correctly initiated and otherwise tries to download the `.git` history and submodules from GH (it might also work without the `.git` history) - the hook script could also be used to automatically update the tour translations if there's an internet connection

**Comment by wilzbach** [comment]
Closing as we seem to not have many improvements over the last months. I would recommend to go with KISS and tag a new release whenever something important is merged.
