### ISSUE TITLE
https://tour.dlang.org/tour/en/basics/ranges

### ISSUE THREAD

**Issue by EmTee70** [stonemaster/dlang-tour#495]
The code seams to miss some essentials.
"by the fact that every number after the first two is the sum of the two preceding ones" ?

ERROR RUNNING:
rdmd playground.d

onlineapp.d(5): Error: function onlineapp.FibonacciRange.empty has no return statement, but is expected to return a value of type bool
onlineapp.d(15): Error: function onlineapp.FibonacciRange.front has no return statement, but is expected to return a value of type int
Failed: ["dmd", "-v", "-o-", "onlineapp.d", "-I."]

**Comment by wilzbach** [comment]
> The code seams to miss some essentials

Yep, this is intended. It's an interactive exercise for the reader. PRs or ideas to make this fact more prominent are welcome.

**Comment by wilzbach** [comment]
Closing due to no response from the submitter.
@EmTee70 the tutorial is a template which can be completed by the reader. If you have ideas to improve the visibility of this fact or change the layout of the tour itself, please feel free to open a new issue(s).
