### ISSUE TITLE
Complete translation

### ISSUE THREAD

**Issue by keito940** [stonemaster/dlang-tour#503]
https://tour.dlang.org/tour/ja/welcome/welcome-to-d
The tour is not completed.

**Comment by wilzbach** [comment]
@keito940 please have a look here:

https://github.com/dlang-tour/japanese/pulls

We are very happy to give you merge rights, so that you could help to move this work forward :)

**Comment by wilzbach** [comment]
Closing this as the Japanese translation is an active WIP project
If you want to help this project you could:
- review & approve open PRs
- do page translations yourself
- get in touch with @kotet who is working very hard on the Japanese translation

![image](https://cloud.githubusercontent.com/assets/4370550/24332380/f3510566-1245-11e7-8a22-60097ab0984b.png)
