### ISSUE TITLE
contributing.md file

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#51]
Github will display a link to this file on every issue & PR - might be a good opportunity to highlight some key points and link to other README's (e.g. the one at public/content)

**Comment by stonemaster** [comment]
That's a nice idea.

**Comment by wilzbach** [comment]
bumping that as stuff like 48 chars for mobile is probably new to potential contributors ;-)

**Comment by wilzbach** [comment]
> bumping that as stuff like 48 chars for mobile is probably new to potential contributors

quickly submitted #66
