### ISSUE TITLE
custom HTML macros

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#55]
I can think of four good examples

1) Alert boxes

![image](https://cloud.githubusercontent.com/assets/4370550/15243267/2bb541f2-1903-11e6-9d63-11b8caec93d7.png)

2) Callouts infos

![image](https://cloud.githubusercontent.com/assets/4370550/15243286/3af555da-1903-11e6-8c75-12b001b27cd1.png)

3) Asides

![image](https://cloud.githubusercontent.com/assets/4370550/15243304/57fa3bfa-1903-11e6-9d42-a29a3c86f1ea.png)

4) Tables

![image](https://cloud.githubusercontent.com/assets/4370550/15243308/5fae6fb0-1903-11e6-8d7a-606c99c454fd.png)

Probably 1,2,3 could be summarized into 2 categories only.

**Comment by stonemaster** [comment]
I think we should rely on standard markdown for defining the content. That way any normal editor will be able to format it locally as well as GitHub in the online editor. Special cases will just make it harder for everyone to understand what is going on. For *VERY* *VERY* important stuff (a table) HTML can be used directly. Also this feature would require changes to vibe.d's md parser (or a custom one). So I don't think the benefits outweigh the drawbacks.

**Comment by wilzbach** [comment]
I reopen this as it seems that we need to find a simple way to have custom HTML macros/templates that allow us to separate HTML from the markdown text and make translations easier (see e.g. #248)

**Comment by stonemaster** [comment]
Agreed that this might be useful. Problem is that would need to either enhance the current vibe.d markdown filter or use another markdown processor that allows more customisation. There currently is just one other markdown parsed listed at code.dlang.org which basically is the vibe.d markdown parser but stripped out of the framework.

**Comment by wilzbach** [comment]
> Agreed that this might be useful. Problem is that would need to either enhance the current vibe.d markdown filter or use another markdown processor that allows more customisation.

Hmm do we really need to touch the Markdown engine? Basically we could apply our macros _before_ converting the text to markdown?
A language that I like for it's simplicity is Liquid (known from Github Pages, Jekyll)

https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
https://github.com/Shopify/liquid/wiki/Liquid-for-Programmers

But basically for the beginning we only need to able to extend something like `{{ download_icon, 'arch_linux' }}`. We could use a simple, recursive regex's to find and replace such occurrences. 

They could be defined in a  `template.yml`

```
download_icon:
<img class="download-icon" src="{{ root }}/img/{{ $1 }}.png
```

I am still worried about rolling our own system here - @stonemaster do you have better ideas? :)

**Comment by stonemaster** [comment]
Unfortunately I have no better idea. But something that resembles liquid in some way is still better than cluttering the content md's with layout html. We should just make sure that we dont't make sure to not make use of those special features too often and try to achieve as much as possible with standard markdown..

**Comment by stonemaster** [comment]
An idea I just had: maybe we could use the Diet templating system? That way we don't need to roll our own system. I don't want to compile necessarily because that makes compilation of the dlang tour really slow. Maybe we can find a way to do that at runtime..
Unfortunately I didn't find any D solution we could use that fits our needs. So either we find something to integrate Diet or we have to roll our own..

**Comment by stonemaster** [comment]
Unfortunately the vibe.d and Diet way won't work. Will try to look into another solution. Currently still the own regex thingie is the best solution..

**Comment by stonemaster** [comment]
I found this one: https://github.com/repeatedly/mustache-d
Must have slipped me but seems to be the right direction for use. It uses the `{{ }}` syntax too and hopefully allows some more stuff than simply replacing text. I'll have a look at it.

**Comment by stonemaster** [comment]
Working on a solution using mustache. Looks promising so far. Should habe something weithin the next days.

**Comment by stonemaster** [comment]
Vibe.d will support markdown tables soon!
 https://github.com/rejectedsoftware/vibe.d/issues/1493
