### ISSUE TITLE
check whether examples are really compiling

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#57]
Before deployment travis should really check whether all code examples run, s.t. like this shouldn't happen ;-)

![image](https://cloud.githubusercontent.com/assets/4370550/15243419/22b24d38-1904-11e6-9263-d8786b5412f4.png)

**Comment by stonemaster** [comment]
That would be useful definitely.

**Comment by stonemaster** [comment]
@wilzbach actually that isn't a compiling error :-) That's how the example works currently..

Still automation is definitely useful!
