### ISSUE TITLE
nav overlaps content

### ISSUE THREAD

**Issue by John-Colvin** [stonemaster/dlang-tour#64]
Only at certain widths. OS X chrome.

![image](https://cloud.githubusercontent.com/assets/1867189/15302010/86615b70-1ba8-11e6-9941-a77f16ce2876.png)

**Comment by wilzbach** [comment]
Probably related to #42

**Comment by stonemaster** [comment]
Weird. It's a bootstrap navbar which should make sure this doesnt happen. I have OS x and chrome so I will be able to check.

**Comment by wilzbach** [comment]
Probably fixable with #202 (official dlang menu)

**Comment by stonemaster** [comment]
Verified on OS X with chrome and Safari. Doesn't happen anymore thanks to #202
