### ISSUE TITLE
Allow language selection

### ISSUE THREAD

**Issue by stonemaster** [stonemaster/dlang-tour#9]
The content and the internal content representation have been designed to allow translations but this should be also reflected in the frontend and made available to users.

**Comment by wilzbach** [comment]
Being able to switch to any language could potentially be difficult as it requires the backend to send in which languages the current page is implemented (a translation might be outdated or incomplete). 
I guess we could just drop the selection idea and show the available languages at the beginning (like the Go Tour). 
Moreover it we use a lot of precious ui space for a feature that is not commonly used. 
Hence I will go ahead and close this, feel free to reopen in case of arguments for such a interactive  selection.

**Comment by stonemaster** [comment]
I fully agree. Good idea.
