### ISSUE TITLE
Add monitoring

### ISSUE THREAD

**Issue by wilzbach** [stonemaster/dlang-tour#95]
Seems like the tour is down for at least the last ten minutes. Just a ping whether your are aware of this?

**Comment by stonemaster** [comment]
No I wasn't. Thanks for the hint. I will reuse this issue for adding monitoring.

**Comment by stonemaster** [comment]
Added monitoring using https://uptimerobot.com/. Checks are in a 5 minute interval and a mail sent when the host is down. Anyone having server credentials could be added as an emergency contact at a later stage.
